### PR TITLE
feat: post show up on home page, able to view post details and delete…

### LINKED ISSUE #3: Posts
- dataProvider
- List.js
- Detail.js
- Post.js
- Post.css

### PR DESCRIPTION
**Pull request by calebsjames**
… a post

### CODE REVIEW

**Review by nathanRomad — APPROVED** [review]
looks good when I logged in.
can see posts.
can delete posts.
can see re-routing when edit is clicked.
can see re-routing when new post is clicked.

**Review by morriscodez — APPROVED** [review]
looks good

**Review by nathanRomad — APPROVED** [review]
testing looks good.
I can update, delete, and create new posts.

**Review by Ccourter11 — APPROVED** [review]
Works on my end!

**Pull request merged**
