### PR TITLE
fix: update form control

### LINKED ISSUE #20: Categories: form fill on edit categories
- edit needs form update, users should not have to re-fill out the form.

### PR DESCRIPTION
**Pull request by nathanRomad**

### CODE REVIEW

**Review by morriscodez — APPROVED** [review]
Form looks solid

**Review by Ccourter11 — COMMENTED** [review]
Checks out

**Review by calebsjames — APPROVED** [review]
Works!

**Review by Ccourter11 — APPROVED** [review]
Works on my end

**Pull request merged**
